---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: result-app-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 32000
  selector:
    name: result-app
...
