---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Workerapp-deployment
  labels:
    name: worker-service
    author: intelliqit
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-app
    spec:
      containers:
        - name: my-workers
          image: dockersamples/examplevotingapp_worker
...